/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Book: typeof import('./src/components/Book.vue')['default']
    Bookshelf: typeof import('./src/components/Bookshelf.vue')['default']
    ChapterSettingsDialog: typeof import('./src/components/ChapterSettingsDialog.vue')['default']
    EditorMenubar: typeof import('./src/components/EditorMenubar.vue')['default']
    EditorPanel: typeof import('./src/components/EditorPanel.vue')['default']
    EditorProgress: typeof import('./src/components/EditorProgress.vue')['default']
    EditorStats: typeof import('./src/components/EditorStats.vue')['default']
    EditorToolbar: typeof import('./src/components/EditorToolbar.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSplitter: typeof import('element-plus/es')['ElSplitter']
    ElSplitterPanel: typeof import('element-plus/es')['ElSplitterPanel']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    IconFont: typeof import('./src/components/IconFont.vue')['default']
    LayoutTool: typeof import('./src/components/LayoutTool.vue')['default']
    NoteChapter: typeof import('./src/components/NoteChapter.vue')['default']
    RadialMenu: typeof import('./src/components/RadialMenu.vue')['default']
    RandomName: typeof import('./src/components/RandomName.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPanel: typeof import('./src/components/SearchPanel.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
    WordCountChart: typeof import('./src/components/WordCountChart.vue')['default']
  }
}
